name = "HDF5Browse"
uuid = "0155c594-5460-11e9-3ffb-e705f8a4e917"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
